### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by richardoppiyo** [leopiresgoss/to-do-list#11]
Your code looks well structured and sleek. However, there are a few issues that we suggest you have a look at:

-The title should not be editable. You might want to use a paragraph tag and don't give it any focus.
-When you click outside the list items, the background color of the list item should be changed. You might want to disable focus whenever a list item loses focus.

**Comment by leopiresgoss** [comment]
Thank you. I've already updated it.
